### PR TITLE
Use @hurumap-ui packages

### PR DESCRIPTION
**Pull request by karimkawambwa**
## Description

Use new packages @hurumap-ui

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by karimkawambwa** [comment]
Ping @KhadijaMahanga @kilemensi @nerdlet

**Review by kilemensi — COMMENTED** [review]
:+1: @karimkawambwa 

1. `Download` (and in turn `Share`) button doesn't work for me.
2. `yarn.lock` needs updating

**Comment by karimkawambwa** [comment]
> 1. `Download` (and in turn `Share`) button doesn't work for me.

@kilemensi  we need to merge this https://github.com/CodeForAfrica/HURUmap-UI/pull/122

**Review by kilemensi — APPROVED** [review]
:rocket: @karimkawambwa

**Pull request merged**
