### PR TITLE
Bump Hurumap UI

### PR DESCRIPTION
**Pull request by karimkawambwa**
## Description

Bump to @codeforafrica/hurumap-ui": "^0.2.8 which should not be using @mikecousins/react-pdf

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — APPROVED** [review]
Bump all backward-compatible dependencies @karimkawambwa 

Screenshot from 2020-03-03 16-57-32

**Comment by kilemensi** [comment]
Anything still pending on this @karimkawambwa?

What was the final decision on mikecousins/react-pdf issue @KhadijaMahanga ?

**Comment by karimkawambwa** [comment]
> Anything still pending on this @karimkawambwa?
> 
> What was the final decision on mikecousins/react-pdf issue @KhadijaMahanga ?

Nothing else pending
I believe @KhadijaMahanga  reverted back to mikecousins/react-pdf

**Comment by karimkawambwa** [comment]
Closing this in favour of https://github.com/TakwimuAfrica/Dashboard/pull/63

**Pull request closed without merging**
