### PR TITLE
Page editor

### PR DESCRIPTION
**Pull request by KhadijaMahanga**
## Description
Remove editor, discussion, comments and author field on contact, index, and legal pages

Fixes # (issue)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

### Update
Screenshot from 2019-09-30 13-09-13

### Before Update
Screenshot from 2019-09-30 13-10-07
Screenshot from 2019-09-30 13-13-54

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — APPROVED** [review]
:rocket: @KhadijaMahanga.

1. I'd be **happier** if we use something permanent... page titles are bound to be change by the comms team without our knowledge.
2. set `git config core.fileMode false` so as to ignore file mode changes (`.gitignore` and `docker-compose.yml` don't have content changes.)

**Comment by KhadijaMahanga** [comment]
@kilemensi changed to using ids

**Review by DavidLemayian — COMMENTED** [review]
What if we created a custom settings page for all these things? :)
https://codex.wordpress.org/Creating_Options_Pages

**Comment by kilemensi** [comment]
> What if we created a custom settings page for all these things? :)
> https://codex.wordpress.org/Creating_Options_Pages

We thought of using Custom Options/Admin pages for things that are customizable/editable @DavidLemayian  e.g. @karimkawambwa is adding a custom admin page to house `charts.json`... This felt like straightforward issue, these pages shouldn't have "body" so to speak... every thing is defined in the custom fields they contain.

But yeah @KhadijaMahanga, options page is a better option in the longer term I guess.

**Pull request merged**
